import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: {
		icon: [
			{
				media: '(prefers-color-scheme: light)',
				url: '/images/favicon.png',
				href: '/images/favicon-light.png'
			},
			{
				media: '(prefers-color-scheme: dark)',
				url: '/images/favicon.png',
				href: '/images/favicon-dark.png'
			}
		]
	}
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
