import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import type { ChildrenProps } from '../@types';
import './globals.css';

const sans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Nextjs Blog',
	description: 'Generated by create next app',
	icons: [
		{
			rel: 'icon',
			type: 'image/png',
			sizes: '32x32',
			url: '/favicon/favicon.ico'
		}
	]
};

const RootLayout = ({ children }: ChildrenProps) => {
	return (
		<html lang="ko">
			<body className={sans.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
